### ISSUE TITLE
How to use the software?

### ISSUE THREAD

**Issue by code-build-deploy-developer** [barnstee/OPCUA2AAS#4]
Hi,

how to use the software? I want to transform an OPC UA info model to aas.

Cheers

**Comment by barnstee** [comment]
Have a look here: https://github.com/barnstee/OPCUA2AAS/blob/3afa511675c3a4c5832b7b548bd9d2ed814aa5e8/StationNodeManager.cs#L139
I.e., you need to use a UA client to call the method on the server to generate the AAS.

But you may also be interested in this tool, which generates an AAS and has even more functionality:
https://github.com/barnstee/UANodesetWebViewer
